### ISSUE TITLE
TypeScript plugin tries to compile cmd file?

### ISSUE THREAD

**Issue by razorree** [palantir/eclipse-typescript#284] opened 2015-10-05 09:40 UTC
I have Enide 2015 and just installed TypeScript plugin from Palantir. NodeJS and TypeScript are installed too (i can call tsc from command line and compile ts files).

However, when i'm trying to run NodeJS project from Enide, there is an error

C:\Users\razor\AppData\Roaming\npm\tsc.cmd:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by derekcicerone** [comment] 2015-12-01 02:03
Sorry, I'm not familiar with Enide. Were you able to resolve this issue?

Closing for now because I don't have enough information to reproduce this issue in a bare Eclipse install.

**Closed by derekcicerone** 2015-12-01 02:03 UTC
