### ISSUE TITLE
File not found when reference is in a parent folder

### ISSUE THREAD

**Issue by amergey** [palantir/eclipse-typescript#280] opened 2015-09-29 14:41 UTC
eclipse typescript is not able to find definition from a parent folder
with 
/// \<reference path="../typings/tsd.d.ts" />; 
An error is displayed:  File:'eclipse:/myproject/typings/tsd.d.ts' not found (the file exist in this location.

if I copy typings within my sources so reference become 
/// \<reference path="./typings/tsd.d.ts" />; 
I works, the file is found.

It seems the culprit is '..' that seems to be not supported

**Comment by BlacKCaT27** [comment] 2015-10-01 17:51
I've noticed this too as of today. This didn't use to occur. Perhaps a bug introduced with the latest update?

**Comment by derekcicerone** [comment] 2015-10-01 20:10
Weird, I don't think anything has changed on the Eclipse side and I don't think the Eclipse plug-in interacts with this support very much (but perhaps I'm wrong). Sorry, I don't have time to look into this for a while but if you figure out the issue, we'd love to accept a PR.

**Comment by BlacKCaT27** [comment] 2015-10-01 20:12
I found that the issue went away if I removed the "source folder(s)" from
the Typescript options menu, which seems to default to the plugin just
scanning the whole project. I couldn't figure out the correct syntax for
specifying multiple folders (which I assume is what I would need to do to
specify two different locations I'd want to reference in ///reference
path...)

**Comment by derekcicerone** [comment] 2015-10-01 20:16
You can use a semicolon delimiter for multiple folders.

**Comment by derekcicerone** [comment] 2015-12-01 02:06
Closing this for now, please feel free to add more info if you think this should be reopened. Afaik all references are handled by the TypeScript language service itself, not the Eclipse plug-in, so this may not be something I could fix in the plug-in.

**Closed by derekcicerone** 2015-12-01 02:06 UTC

**Comment by esc-mhild** [comment] 2018-04-12 18:38
The issue still exists in 1.8.0.v20160504-1733. The problem is not related to any occurrence to "..", but only to paths that ascend beyond a configured source folder. Ascending by ".." within a source folder works fine.

Bug or feature?
