### ISSUE TITLE
Support Typescript v2.0

### ISSUE THREAD

**Issue by nchen63** [palantir/eclipse-typescript#331] opened 2016-09-02 21:42 UTC

**Comment by caugner** [comment] 2016-09-27 10:54
@derekcicerone Any ideas what needs to be done in order to support TypeScript 2.0?

**Comment by derekcicerone** [comment] 2016-10-11 17:45
Sorry, I'm not a maintainer on this project any longer. Perhaps the current maintainers could chime in...

**Comment by adidahiya** [comment] 2016-10-12 14:37
tsconfig.json support is here: https://github.com/palantir/eclipse-typescript/pull/323

@nchen63 have you been able to run this plugin with TS 2.0? if not, what errors does it produce?

**Comment by david-bouyssie** [comment] 2016-10-15 13:39
:+1:

**Comment by nchen63** [comment] 2016-10-16 01:36
@adidahiya did not realize that tsconfig was supported. haven't tried it yet

**Comment by lgrignon** [comment] 2017-01-09 13:36
As requested by @sixinli, we should support globs in `tsconfig.json` as well.

**Comment by sixinli** [comment] 2017-01-11 22:14
closing this with #339, add https://github.com/palantir/eclipse-typescript/issues/342 to track glob support

**Closed by sixinli** 2017-01-11 22:14 UTC

**Comment by david-bouyssie** [comment] 2017-01-18 16:46
Nice work !

Any plan to release it on http://eclipse-update.palantir.com/ ?

**Comment by sixinli** [comment] 2017-01-18 19:41
@david-bouyssie thanks for checking, we are still figuring out new way of updating the site, for now you might need to build the package locally for use

**Comment by david-bouyssie** [comment] 2017-01-19 17:02
I tried to build and install the plugin.
I have now a successful build.
However I'm not able to install it in Eclipse.
I have the following error message:

> Cannot complete the request.  See the error log for details.
> TypeScript will be ignored because it is already installed, and updates are not permitted.

**Comment by Rouche** [comment] 2017-01-19 17:06
Uninstall it first, (Help->Iinstallation Details) and remove the com.palantir.typescript._xxxx directory manually in \plugins.
restart eclipse with -clean.

**Comment by david-bouyssie** [comment] 2017-01-19 17:27
Did it. Installation is ok now.

However I'm stuck at the running time now.
If I try to open a TS file I have the following error.

`Failed to create the part's controls`

```
java.lang.IllegalStateException: The node process has crashed.
	at com.palantir.typescript.services.Bridge.processRequest(Bridge.java:133)
	at com.palantir.typescript.services.Bridge.call(Bridge.java:95)
	at com.palantir.typescript.services.classifier.Classifier.getClassificationsForLines(Classifier.java:50)
	at com.palantir.typescript.text.reconciler.PresentationReconciler.classifyLines(PresentationReconciler.java:252)
	at com.palantir.typescript.text.reconciler.PresentationReconciler.createPresentation(PresentationReconciler.java:222)
	at com.palantir.typescript.text.reconciler.PresentationReconciler.processEvent(PresentationReconciler.java:123)
	at com.palantir.typescript.text.reconciler.PresentationReconciler.access$0(PresentationReconciler.java:119)
	at com.palantir.typescript.text.reconciler.PresentationReconciler$MyTextListener.textChanged(PresentationReconciler.java:310)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2826)
	at org.eclipse.jface.text.TextViewer.invalidateTextPresentation(TextViewer.java:3478)
	at org.eclipse.jface.text.TextViewer.initializeWidgetContents(TextViewer.java:3525)
	at org.eclipse.jface.text.TextViewer.setVisibleDocument(TextViewer.java:3564)
	at org.eclipse.jface.text.TextViewer.setDocument(TextViewer.java:2934)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:643)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:591)
	at org.eclipse.ui.texteditor.AbstractTextEditor.initializeSourceViewer(AbstractTextEditor.java:4050)
```

I tried to upgrade NodeJS to the latest available version and the problem is still there.

**Comment by Rouche** [comment] 2017-01-19 17:37
https://github.com/palantir/eclipse-typescript/issues/237

Follow instruction in wiki/readme.md how to build, very carefully. 
Need to do it perfect clean and of course you have to go get TypeScript sources from github.

**Comment by david-bouyssie** [comment] 2017-01-19 17:59
I downloaded the latest version of this repo and just did a "mvn package" on it.
I think I will wait for an a pre-built version.

Thanks !
